version: '3.5'
services:
  milvus:
    image: milvusdb/milvus:v2.3.3
    container_name: milvus-standalone
    restart: always
    ports:
      - "19530:19530"
      - "9091:9091"
    volumes:
      - ./volumes/db:/var/lib/milvus/db
    command: ["milvus", "run", "standalone"]
